// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseFolder() {
  return window['go']['main']['App']['BrowseFolder']();
}

export function GetActivity() {
  return window['go']['main']['App']['GetActivity']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetWatchStatus() {
  return window['go']['main']['App']['GetWatchStatus']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartWatching() {
  return window['go']['main']['App']['StartWatching']();
}

export function StopWatching() {
  return window['go']['main']['App']['StopWatching']();
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}
