// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseFolder():Promise<string>;

export function GetActivity():Promise<Array<main.ActivityEntry>>;

export function GetConfig():Promise<main.Config>;

export function GetWatchStatus():Promise<boolean>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function StartWatching():Promise<void>;

export function StopWatching():Promise<void>;

export function TestConnection():Promise<main.ConnectionResult>;
